---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-expose
  namespace: default
  labels:
    app: mysql-service
spec:
  ports:
  - name: mysql-service
    protocol: TCP
    port: 31703
    targetPort: 3306
    nodePort: 31703
  selector:
    app: mysql-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-service
  clusterIP: None
  selector:
    app: mysql-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mysql-service
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: mysql-service
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "dbpass"
        - name: MYSQL_DATABASE
          value: "dev"
  podManagementPolicy: "Parallel"